services:
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    hostname: kafka
  producer:
    container_name: producer
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka
  offline-store:
    container_name: offline
    image: postgres
    hostname: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: offline_store
  feast:
    container_name: feast
    build:
      dockerfile: ./Dockerfile
    ports:
      - '6566:6566'
    depends_on:
      - offline-store
    command:
      - "feast"
      - "--feature-store-yaml"
      - "/home/demo/feature_repo/feature_store.yaml"
      - "serve"
      - "--host"
      - "0.0.0.0"
    working_dir: /home/demo/feature_repo
